const types = {
    LOAD_CUISINES: 'LOAD_CUISINES',
    CUISINES_SUCCESS: 'CUISINES_SUCCESS',
    CUISINES_ERROR: 'CUISINES_ERROR',
    SEARCH_CUISINE: 'SEARCH_CUISINE',
    SET_CUISINES: 'SET_CUISINES'
};


export default types;