const types = {
    FETCH_LEFTPANEL: 'FETCH_LEFTPANEL',
    SUCCESS_LEFTPANEL: 'SUCCESS_LEFTPANEL',
    ERROR_LEFTPANEL: 'ERROR_LEFTPANEL',
    FETCH_RIGHTPANEL: 'FETCH_RIGHTPANEL',
    SUCCESS_RIGHTPANEL: 'SUCCESS_RIGHTPANEL',
    ERROR_RIGHTPANEL: 'ERROR_RIGHTPANEL',
    FETCH_PANELS: 'FETCH_PANELS',
    FETCH_PANEL_SUCCESS: 'FETCH_PANEL_SUCCESS',
    FETCH_PANEL_ERROR: 'FETCH_PANEL_ERROR'
};

export default types;