const types = {
  UPDATE_FILTER: 'UPDATE_FILTER',
  ENABLE_FILTERS: 'ENABLE_FILTERS',
  DISABLE_FILTERS: 'DISABLE_FILTERS',
  DATA_LOADING: 'DATA_LOADING',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_ERROR: 'DATA_ERROR',
  RESET_FILTER: 'RESET_FILTER'
};
export default types;
